### PR TITLE
Make task processing crash safe

### PR DESCRIPTION
**Pull request by markshust**
fixes issue https://github.com/firebase/firebase-work-queue/issues/3

### CODE REVIEW

**Comment by markoshust** [comment]
Updated my pr with couple minor updates for code formatting

**Comment by markoshust** [comment]
This is a big code update that adds in crash-safe logic and timestamps, and fixed tab vs. space indent probs. If it's too much just deny this PR and reference my repo.

**Comment by drtriumph** [comment]
Thank you, we appreciate your efforts here - we've just released a far more comprehensive version of this example which solves this issue and goes further - including an error callback as well as a callback to report progress on the task. There're also a fair number of edge-cases that have been ironed out over the original, rather basic example. Let me know what you think: https://github.com/firebase/firebase-queue

**Comment by markoshust** [comment]
Thanks, I saw this come through the pipes yesterday. It's great. I put a deprecated notice on my script that references this one. Thanks a bunch, hope I provided some ideas here!

**Pull request closed without merging**
